version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - /var/tmp/docker/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    hostname: postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - /var/tmp/docker/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
